# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
title : Juan P. Schwindt
production_url : http://www.schwindt.org
description: "Hackeando Ruby desde Buenos Aires, Argentina"
permalink: /posts/:title
disqus_shortname: jschwindtblog
analytics: UA-4532575-1
author :
  name : Juan Schwindt
  github : jschwindt
  twitter : jschwindt
  email: juan@schwindt.org

# Build settings
markdown: kramdown
